# Remove an Web ALB
- community.aws.elb_application_lb:
    name: "{{ web_alb.load_balancer_name }}"
    state: absent

# # Remove an App ALB
# - community.aws.elb_application_lb:
#     name: "{{ web_alb.load_balancer_name }}"
#     state: absent

- name: Destroy a target group with Instance IDs
  community.aws.elb_target_group:
    name: "{{ web_elb_tg_name }}"
    protocol: http
    port: 80
    vpc_id: "{{ vpc.vpc.id }}"
    targets:
      - Id: "{{ web_instance_1.instances[0].instance_id }}"
        Port: 80
      - Id: "{{ web_instance_2.instances[0].instance_id }}"
        Port: 80
    state: absent
    wait_timeout: 200