# Remove an App ALB
- community.aws.elb_application_lb:
    name: "ansible-{{ deploy_environment }}-app-elb"
    state: absent
    region: "{{ region }}"

# Remove an Web ALB
- community.aws.elb_application_lb:
    name: "ansible-{{ deploy_environment }}-web-elb"
    state: absent
    region: "{{ region }}"

# Remove an Web ALB TG
- name: Destroy a Web target group with Instance IDs
  community.aws.elb_target_group:
    name: "Ansible-{{ deploy_environment }}-Web-TG"
    state: absent
    region: "{{ region }}"
    wait_timeout: 200

# Remove an App ALB TG
- name: Destroy a App target group with Instance IDs
  community.aws.elb_target_group:
    name: "Ansible-{{ deploy_environment }}-App-TG"
    state: absent
    region: "{{ region }}"
    wait_timeout: 200