- name: Terminate Ec2 instances that are part 
  amazon.aws.ec2_instance:
    region: "{{ region }}"
    state: 'absent'
    instance_ids: 
    - "{{ groups['web_servers'] }}"
    - "{{ groups['app_servers'] }}"
    - "{{ groups['bastion_hosts'] }}"

