- name: remove the DB instance without a final snapshot
  community.aws.rds_instance:
    id: "ansible-{{ deploy_environment }}-db"
    state: absent
    region: "{{ region }}"
    skip_final_snapshot: True

- name: remove the DB Subnet Group 
  community.aws.rds_subnet_group:
    name: ansible-{{ deploy_environment }}-db-subnet-group
    state: absent
    region: "{{ region }}"
