- name: remove the DB instance without a final snapshot
  community.aws.rds_instance:
    id: "ansible-{{ deploy_environment }}-db"
    state: absent
    region: "{{ region }}"
    skip_final_snapshot: True