- name: Associate private subent as DB Subnet Group 
  community.aws.rds_subnet_group:
    state: present
    name: ansible-{{ deploy_environment }}-db-subnet-group
    description: Associate subent as DB Subnet Group
    region: "{{ region }}"    
    subnets:
      - "{{ db_subnet_1.subnet.id }}"
      - "{{ db_subnet_2.subnet.id }}"
    # tags:
    #   Name: "ansible-{{ deploy_environment }}-db-subnet-group"
    #   environ: "{{ deploy_environment }}"
    #   controlled_by: ansible
  register: db_subnet_group
