- hosts: local
  tasks:
  - name: Bastion Host On public Subnet 1
    amazon.aws.ec2_instance:
      name: "dev-Bastion-Host-1"
      key_name: "dev-private-key"
      vpc_subnet_id: "subnet-05cec7bb0cdce588c"
      instance_type: "t2.micro"
      security_group: "Ansible-dev-WEB-SG"
      network:
        assign_public_ip: true
      image_id: "ami-0cff7528ff583bf9a"
      tags:
        Environment: "dev"
        Group: Bastion
    register: ec2
    

  - name: Add the newly created EC2 instance(s) to the local host group
    lineinfile: 
      path: "inventory/ec2"
      insertafter: '^\[bastion_hosts\]' 
      line: "{{ item.public_ip_address}} ansible_user=ec2-user ansible_ssh_private_key_file=keys/dev-private-key.pem ansible_ssh_extra_args='-o StrictHostKeyChecking=no'"
    with_items: "{{ ec2.instances }}"
  - meta: refresh_inventory
  - pause:
      seconds: 30
