- name: Create a target group with Instance IDs
  community.aws.elb_target_group:
    name: "{{ web_elb_tg_name }}"
    protocol: http
    port: 80
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ region }}"
    targets:
      - Id: "{{ web_instance_1.instances[0].instance_id }}"
        Port: 80
      - Id: "{{ web_instance_2.instances[0].instance_id }}"
        Port: 80
    state: present
    tags:
      Name: "{{ web_elb_tg_name }}"
      environ: "{{ deploy_environment }}"
      controlled_by: ansible
    wait_timeout: 200

