- name: Security Group Configuration for App Tier
  amazon.aws.ec2_group:
    name: "{{ app_sg_name }}"
    description: Ansible Security Group for App Tier Allowing All Ports from App ELB SG
    vpc_id: "{{ vpc_id }}"
    region: "{{ region }}"
    rules:
      - proto: tcp
        ports:
        - 0-65535
        group_name: "{{ app_elb_sg.group_name }}"
        rule_desc: allow all ports from App ELB Security group
      - proto: tcp
        ports:
        - 22
        group_name: "{{ bastion_sg.group_name }}"
        rule_desc: allow SSH From Bastion Host

    tags:
      Name: "{{ app_sg_name }}"
      environ: "{{ deploy_environment }}"
      controlled_by: ansible
  register: app_sg
