- name: Security Group Configuration for Bastion Host
  amazon.aws.ec2_group:
    name: "{{ bastion_sg_name }}"
    description: Ansible Security Group for Bastion Hosts Allowing SSH Connection
    vpc_id: "{{ vpc_id }}"
    region: "{{ region }}"
    rules:
      - proto: tcp
        ports:
        - 22
        cidr_ip: 0.0.0.0/0
        rule_desc: allow all on port 22
    tags:
      Name: "{{ bastion_sg_name }}"
  register: bastion_sg
