- name: Security Group Configuration for Web Tier
  amazon.aws.ec2_group:
    name: "{{ web_sg_name }}"
    description: Ansible Security Group for Web Tier Allowing HTTP Port from Web ELB SG
    vpc_id: "{{ vpc_id }}"
    region: "{{ region }}"
    rules:
      - proto: tcp
        ports:
        - 80
        group_name: "{{ web_elb_sg.group_name }}"
        rule_desc: allow Web ELB on port 80
      - proto: tcp
        ports:
        - 22
        group_name: "{{ bastion_sg.group_name }}"
        rule_desc: allow SSH From Bastion Host
    tags:
      Name: "{{ web_sg_name }}"
      environ: "{{ deploy_environment }}"
      controlled_by: ansible
  register: web_sg
