- name: Public Subnet Route Configuration
  ec2_vpc_route_table:
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ region }}"
    subnets:
      - "{{ public_subnet_1.subnet.id }}"
      - "{{ public_subnet_2.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw.gateway_id  }}"
    tags:
      Name: "Ansbile {{ deploy_environment }} Public Subent Route Table"
      environ: "{{ deploy_environment }}"
      controlled_by: ansible

- name: Private Subnet Route Configuration Zone 1
  ec2_vpc_route_table:
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ region }}"
    subnets:
      - "{{ web_subnet_1.subnet.id }}"
      - "{{ app_subnet_1.subnet.id }}"
      - "{{ db_subnet_1.subnet.id }}"
    tags:
      Name: "Ansbile {{ deploy_environment }} Private Subent Route Table Z1"
      environ: "{{ deploy_environment }}"
      controlled_by: ansible

- name: Private Subnet Route Configuration Zone 2
  ec2_vpc_route_table:
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ region }}"
    subnets:
      - "{{ web_subnet_2.subnet.id }}"
      - "{{ app_subnet_2.subnet.id }}"
      - "{{ db_subnet_2.subnet.id }}"
    tags:
      Name: "Ansbile {{ deploy_environment }} Private Subent Route Table Z2"
      environ: "{{ deploy_environment }}"
      controlled_by: ansible
