- name: create VPC
  ec2_vpc_net:
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr }}"
    region: "{{ region }}"
    state: present
    tags:
      Name: "{{ vpc_name }}"
      environ: "{{ deploy_environment }}"
      controlled_by: ansible
  register: vpc
