---
- name: Refresh Dynamic Inventory file
  meta: refresh_inventory

- pause:
    seconds: 30

- name: copy private key to the bastion host
  copy:
    src: "keys/{{ deploy_environment }}-private-key.pem"
    dest: "~/.ssh/{{ deploy_environment }}-private-key.pem"
    mode: '0600'
    
- name: Update application load balancer in web server
  shell: |
    ssh -i ~/.ssh/{{ deploy_environment }}-private-key.pem -o StrictHostKeyChecking=no ec2-user@{{ item }} << EOF
      ls -la;
      sudo cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.backup;
      sudo sed -i "s|proxy_pass .*| proxy_pass http://{{ groups['application_lb'] | first }};|g" /etc/nginx/nginx.conf;
      sudo systemctl restart nginx;
    EOF
  with_items:
  - "{{ groups['web_servers'] }}"


- name: Update RDS endpoint in Apache Server.
  shell: |
    ssh -i ~/.ssh/{{ deploy_environment }}-private-key.pem -o StrictHostKeyChecking=no ec2-user@{{ item }} << EOF
      ls -la;
      sudo cp /var/www/html/phpMyAdmin/config.sample.inc.php /var/www/html/phpMyAdmin/config.inc.php;
      sed -i "s|localhost|{{ groups['db_servers'][0] }}|g" /var/www/html/phpMyAdmin/config.inc.php; 
      sudo systemctl restart httpd;
    EOF
  with_items:
  - "{{ groups['app_servers'] }}"
