- name: App Instance on Private Subnet 1
  amazon.aws.ec2_instance:
    name: "{{ deploy_environment }}-App-Instance-1"
    vpc_subnet_id: "{{ app_subnet_1.subnet.id }}"
    instance_type: "{{ app_instance_type }}"
    key_name: "{{ deploy_environment }}-private-key"
    security_group: "{{ app_sg.group_id }}"
    image_id: "{{ app_ami }}"
    state: running
    user_data: "{{ lookup('file', 'web_user_data.sh') }}"
    tags:
      Environment: "{{ deploy_environment }}"
      Group: AppTier
  register: app_instance_1

- name: App Instance on Private Subnet 2
  amazon.aws.ec2_instance:
    name: "{{ deploy_environment }}-App-Instance-2"
    vpc_subnet_id: "{{ app_subnet_2.subnet.id }}"
    key_name: "{{ deploy_environment }}-private-key"
    instance_type: "{{ app_instance_type }}"
    security_group: "{{ app_sg.group_id }}"
    image_id: "{{ app_ami }}"
    state: running
    user_data: "{{ lookup('file', 'web_user_data.sh') }}"
    tags:
      Environment: "{{ deploy_environment }}"
      Group: AppTier
  register: app_instance_2

- name: Add the App Server EC2 instance to Dynamic Inventory
  lineinfile: 
    path: "inventory/ec2"
    insertafter: '^\[app_servers\]' 
    line: "{{ app_instance_1.instances[0].private_ip_address}}"

- name: Add the App EC2 instance to Dynamic Inventory
  lineinfile: 
    path: "inventory/ec2"
    insertafter: '^\[app_servers\]' 
    line: "{{ app_instance_2.instances[0].private_ip_address}}"