- name: Bastion Host On public Subnet 1
  amazon.aws.ec2_instance:
    name: "{{ deploy_environment }}-Bastion-Host-1"
    key_name: "{{ deploy_environment }}-private-key"
    vpc_subnet_id: "{{ public_subnet_1.subnet.id }}"
    instance_type: "{{ bastion_instance_type }}"
    security_group: "{{ bastion_sg.group_id }}"
    network:
      assign_public_ip: true
    image_id: "{{ bastion_ami }}"
    region: "{{ region }}"
    state: "running"
    tags:
      Environment: "{{ deploy_environment }}"
      Group: Bastion
  register: bastion_instance_1

- name: Add the Bastion EC2 instance to Dynamic Inventory
  lineinfile: 
    path: "inventory/ec2"
    insertafter: '^\[bastion_hosts\]' 
    line: "{{ bastion_instance_1.instances[0].public_ip_address}} ansible_user=ec2-user ansible_ssh_private_key_file=keys/{{ deploy_environment }}-private-key.pem ansible_ssh_extra_args='-o StrictHostKeyChecking=no'"

# - name: Bastion Host On public Subnet 2
#   amazon.aws.ec2_instance:
#     name: "{{ deploy_environment }}-Bastion-Host-2"
#     key_name: "{{ deploy_environment }}-private-key"
#     vpc_subnet_id: "{{ public_subnet_2.subnet.id }}"
#     instance_type: "{{ bastion_instance_type }}"
#     security_group: "{{ bastion_sg.group_id }}"
#     network:
#       assign_public_ip: true
#     image_id: "{{ bastion_ami }}"
#     tags:
#       Environment: "{{ deploy_environment }}"
#       Group: Bastion
#   register: bastion_instance_2
