- name: Create a new EC2 key
  ec2_key:
      name: "{{ deploy_environment }}-private-key-{{ region }}"
      region: "{{ region }}"
  register: bastion_key
 
- name: Save Bastion private key to local
  copy: content="{{ bastion_key.key.private_key }}" dest="./keys/{{ deploy_environment }}-private-key-{{ region }}.pem" mode=0600
  when: bastion_key.changed
